### ISSUE TITLE
How to get coordinates of cropped image in the original image

### ISSUE THREAD

**Issue by JakobStadlhuber** [hnvn/flutter_image_cropper#253]
Is there a way to get the coordinates of the cropped image in the original image?
Currently only the croppedFile as file will be returned, is it possible to get the coordinate information too?

**Comment by JakobStadlhuber** [comment]
fixed it: https://github.com/JakobStadlhuber/flutter_image_cropper

**Comment by Umar1312** [comment]
Is there any update on this. I need to x and y co-ordinates of the cropped image?

**Comment by JakobStadlhuber** [comment]
try to add this to your pubspec dependencies:
```
  image_cropper:
    git:
      url: https://github.com/JakobStadlhuber/flutter_image_cropper.git
      ref: master
```
