### ISSUE TITLE
Build failure: duplicate classes

### ISSUE THREAD

**Issue by reyleo** [hnvn/flutter_image_cropper#29]
Flutter dependencies:
```
  flutter:
    sdk: flutter
  sqflite: ^1.1.0
  image_picker: ^0.5.0
  path_provider:
```
When I add new dependency
```  
  image_cropper: ^1.0.0
```

build fails
with error
Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
Attached diff of debug dependencies:
[diff-y.txt](https://github.com/hnvn/flutter_image_cropper/files/2935621/diff-y.txt)
