### ISSUE TITLE
Ability to change button background color and color of the %

### ISSUE THREAD

**Issue by momoDragon** [hnvn/flutter_image_cropper#62]
![Screenshot_90](https://user-images.githubusercontent.com/40727575/60956261-0856a100-a335-11e9-87ad-dc20ca2107b7.png)

Cant seem to find a parameter to change the color of the purple part.

**Comment by himanshu096** [comment]
@momoDragon  You can use the updated library by replacing this code in your pubspec.yaml to test if it's working for you or not.

```
  image_cropper:
    git:
      url: git://github.com/devslane/flutter_image_cropper
      ref: master
```
